//
//  AddNewLocationPresenter.swift
//  Weather
//
//  Created by Ahmed Ali Henawey on 20/04/2018.
//  Copyright (c) 2018 Ahmed Ali Henawey. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddNewLocationPresentationLogic
{
  func presentCityName(response: AddNewLocation.Location.GeoCoder.Response)
    func presentCityAdded()
    func presentError(error: Swift.Error)
}

class AddNewLocationPresenter: AddNewLocationPresentationLogic
{
  weak var viewController: AddNewLocationDisplayLogic?
  
  // MARK: Presentation
    func presentCityName(response: AddNewLocation.Location.GeoCoder.Response) {
        // Place details
        let placeMark = response.placemark
        
        // City
        if let city = placeMark.addressDictionary!["City"] as? String {
            viewController?.displayCityName(viewModel: AddNewLocation.Location.GeoCoder.ViewModel(cityName: city))
        } else {
            viewController?.displayCityName(viewModel: AddNewLocation.Location.GeoCoder.ViewModel(cityName: "Unknown City"))
        }
    }
    
    func presentCityAdded() {
        viewController?.displayCityAdded()
    }
    
    
    func presentError(error: Error) {
         viewController?.displayError(title: NSLocalizedString("Error", comment: "Error"), message: error.localizedDescription)
    }
}
