//
//  AddNewLocationViewController.swift
//  Weather
//
//  Created by Ahmed Ali Henawey on 20/04/2018.
//  Copyright (c) 2018 Ahmed Ali Henawey. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import MapKit

protocol AddNewLocationDisplayLogic: class
{
    func displayCityName(viewModel: AddNewLocation.Location.GeoCoder.ViewModel)
    func displayCityAdded()
    func displayError(title: String, message: String)
}

class AddNewLocationViewController: UIViewController, AddNewLocationDisplayLogic
{
    var interactor: AddNewLocationBusinessLogic?
    var router: (NSObjectProtocol & AddNewLocationRoutingLogic & AddNewLocationDataPassing)?
    
    var currentAnnotation: MKPointAnnotation? {
        didSet {
            let userSelectedAnnotation = currentAnnotation != nil
            confrimButton.isEnabled = userSelectedAnnotation
        }
    }
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = AddNewLocationInteractor()
        let presenter = AddNewLocationPresenter()
        let router = AddNewLocationRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    
    @IBAction func handleUserLocationSelection(_ sender: UITapGestureRecognizer) {
        let location = sender.location(in: mapView)
        let coordinate = mapView.convert(location,toCoordinateFrom: mapView)
        
        currentAnnotation = MKPointAnnotation()
        currentAnnotation!.coordinate = coordinate
        
        interactor?.getCityName(request: AddNewLocation.Location.GeoCoder.Request(coordinate: coordinate))
    }
    
    @IBAction func ConfrimTouchUpInside(_ sender: Any) {
        interactor?.addCity(request: AddNewLocation.Location.Add.Request(cityName: currentAnnotation?.title, cityCoordinate: currentAnnotation?.coordinate))
    }
    
    // MARK: Displaying
    
    @IBOutlet weak var confrimButton: UIButton!
    @IBOutlet weak var mapView: MKMapView!
    @IBOutlet weak var cityName: UILabel!
    
    
    func displayCityAdded() {
        navigationController?.popViewController(animated: true)
    }
    
    func displayError(title: String, message: String) {
        if let lastAnnotation = currentAnnotation {
            mapView.removeAnnotation(lastAnnotation)
        }
        
        let alertController = UIAlertController(title: title, message: message, preferredStyle: .alert)
        alertController.addAction(UIAlertAction(title: "OK", style: .cancel, handler: nil))
        present(alertController, animated: true, completion: nil)
    }
    
    func displayCityName(viewModel: AddNewLocation.Location.GeoCoder.ViewModel) {
        if let lastAnnotation = currentAnnotation {
            mapView.removeAnnotation(lastAnnotation)
        }
        
        // Add annotation:
        currentAnnotation?.title = viewModel.cityName
        mapView.addAnnotation(currentAnnotation!)
        
        cityName.text = viewModel.cityName
    }
}
