//
//  AddNewLocationWorker.swift
//  Weather
//
//  Created by Ahmed Ali Henawey on 20/04/2018.
//  Copyright (c) 2018 Ahmed Ali Henawey. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CoreLocation

class AddNewLocationWorker
{
    fileprivate let dataSource: CitiesStoreProtocol
    
    init(dataSource: CitiesStoreProtocol = UserDefaultCitiesDataStore()) {
        self.dataSource = dataSource
    }
    
    func addCity(city: Home.Location.City,
                 completionHandler: @escaping (Result<Home.Location.City,CitiesStoreError>)->()) {
        if CLLocationCoordinate2DIsValid(city.coordinates) {
            dataSource.create(city: city, completionHandler: completionHandler)
        } else {
            completionHandler(.failure(CitiesStoreError.cannotCreate("Coordinates: \(city.coordinates) is not valid")))
        }
    }
}
