//
//  WeatherDetailsViewController.swift
//  Weather
//
//  Created by Ahmed Ali Henawey on 21/04/2018.
//  Copyright (c) 2018 Ahmed Ali Henawey. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WeatherDetailsDisplayLogic: class
{
    func displayWeatherDetails(viewModel: WeatherDetails.ViewModel)
    func displayError(title: String, message: String)
}

class WeatherDetailsViewController: UITableViewController, WeatherDetailsDisplayLogic
{
    var interactor: WeatherDetailsBusinessLogic?
    var router: (NSObjectProtocol & WeatherDetailsRoutingLogic & WeatherDetailsDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = WeatherDetailsInteractor()
        let presenter = WeatherDetailsPresenter()
        let router = WeatherDetailsRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    @IBOutlet weak var temperatureLabel: UILabel!
    @IBOutlet weak var humidityLabel: UILabel!
    @IBOutlet weak var precipitationLabel: UILabel!
    @IBOutlet weak var windSpeedLabel: UILabel!
    @IBOutlet weak var windDegreesLabel: UILabel!
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        loadForecastForSelectedCity()
    }
    
    // MARK: Do something
    
    func loadForecastForSelectedCity()
    {
        interactor?.loadForecast()
    }
    
    func displayWeatherDetails(viewModel: WeatherDetails.ViewModel)
    {
        title = viewModel.cityName
        temperatureLabel.text = viewModel.temperature
        humidityLabel.text = viewModel.humidity
        precipitationLabel.text = viewModel.precipitation
        windSpeedLabel.text = viewModel.windSpeed
        windDegreesLabel.text = viewModel.windDegrees
    }
    
    func displayError(title: String, message: String){
        let alertController = UIAlertController(title: title, message: message, preferredStyle: .alert)
        alertController.addAction(UIAlertAction(title: "OK", style: .cancel, handler: nil))
        present(alertController, animated: true, completion: nil)
    }
}
