//
//  HomeWorker.swift
//  Weather
//
//  Created by Ahmed Ali Henawey on 18/04/2018.
//  Copyright (c) 2018 Ahmed Ali Henawey. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class HomeWorker
{
    fileprivate let dataSource: CitiesStoreProtocol
    
    init(dataSource: CitiesStoreProtocol = UserDefaultCitiesDataStore()) {
        self.dataSource = dataSource
    }
    
    func removeCity(id: String,
                    completionHandler: @escaping (Result<Home.Location.City,CitiesStoreError>)->()) {
        dataSource.delete(id: id, completionHandler: completionHandler)
    }
    
    func removeAllCities(completionHandler: @escaping (Result<Void,CitiesStoreError>)->()) {
        dataSource.clearCities(completionHandler: completionHandler)
    }
    
    func getCities(completionHandler: @escaping (Result<[Home.Location.City],CitiesStoreError>)->()) {
        dataSource.fetch(completionHandler: completionHandler)
    }
    
}
