//
//  HomePresenter.swift
//  Weather
//
//  Created by Ahmed Ali Henawey on 18/04/2018.
//  Copyright (c) 2018 Ahmed Ali Henawey. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic
{
    func presentBookmarkedLocations(response: Home.Location.Retrieve.Response)
    func presentBookmarkedLocationDeleted(response: Home.Location.Remove.Response)
    func presentShowCityPrepared()
    func presentError(error: LocalizedError)
}

class HomePresenter: HomePresentationLogic
{
    weak var viewController: HomeDisplayLogic?
    
    // MARK: Do something
    
    func presentBookmarkedLocations(response: Home.Location.Retrieve.Response)
    {
        let viewModel = Home.Location.ViewModel(cities: response.cities)
        viewController?.displayBookmarkedLocations(viewModel: viewModel)
    }
    
    func presentBookmarkedLocationDeleted(response: Home.Location.Remove.Response) {
        let viewModel = Home.Location.Remove.ViewModel(cityIndex: response.cityIndex, cityIndexPath: IndexPath(row: response.cityIndex, section: 0))
        viewController?.displayCityDeleted(viewModel: viewModel)
    }
    
    func presentError(error: LocalizedError) {
        viewController?.displayError(title: NSLocalizedString("Error", comment: "Error"), message: error.localizedDescription)
    }
    
    func presentShowCityPrepared() {
        viewController?.displaySelectedCityPrepared()
    }
}
