//
//  HomePresenter.swift
//  Weather
//
//  Created by Ahmed Ali Henawey on 18/04/2018.
//  Copyright (c) 2018 Ahmed Ali Henawey. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic
{
  func presentBookmarkedLocations(response: Home.Location.Response)
}

class HomePresenter: HomePresentationLogic
{
  weak var viewController: HomeDisplayLogic?
  
  // MARK: Do something
  
  func presentBookmarkedLocations(response: Home.Location.Response)
  {
    let viewModel = Home.Location.ViewModel()
    viewController?.displayBookmarkedLocations(viewModel: viewModel)
  }
}
