//
//  HomePresenterTests.swift
//  Weather
//
//  Created by Ahmed Ali Henawey on 18/04/2018.
//  Copyright (c) 2018 Ahmed Ali Henawey. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Weather
import XCTest
import CoreLocation

class HomePresenterTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: HomePresenter!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupHomePresenter()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupHomePresenter()
  {
    sut = HomePresenter()
  }
  
  // MARK: Test doubles
  
  class HomeDisplayLogicSpy: HomeDisplayLogic
  {
    var displayBookmarkedLocationsCalled = false
    
    func displaySelectedCityPrepared() {}
    
    func displayCityDeleted(viewModel: Home.Location.Remove.ViewModel) {}
    
    func displayError(title: String, message: String) {}
    
    func displayBookmarkedLocations(viewModel: Home.Location.ViewModel) {
        displayBookmarkedLocationsCalled = true
    }
  }
  
  // MARK: Tests
  
  func testPresentBookmarkedLocations()
  {
    // Given
    let spy = HomeDisplayLogicSpy()
    sut.viewController = spy
    let response = Home.Location.Retrieve.Response(cities: [Home.Location.City(code: 0, name: "test", coordinates: CLLocationCoordinate2D(latitude: 0, longitude: 0))])
    
    // When
    sut.presentBookmarkedLocations(response: response)
    
    // Then
    XCTAssertTrue(spy.displayBookmarkedLocationsCalled, "presentSomething(response:) should ask the view controller to display the result")
  }
}
