//
//  HomeInteractorTests.swift
//  Weather
//
//  Created by Ahmed Ali Henawey on 18/04/2018.
//  Copyright (c) 2018 Ahmed Ali Henawey. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Weather
import XCTest

class HomeInteractorTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: HomeInteractor!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupHomeInteractor()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupHomeInteractor()
  {
    sut = HomeInteractor()
  }
  
  // MARK: Test doubles
  
  class HomePresentationLogicSpy: HomePresentationLogic
  {
    
    var presentBookmarkedLocationsCalled = false
    
    func presentBookmarkedLocationDeleted(response: Home.Location.Remove.Response) {}
    
    func presentShowCityPrepared() {}
    
    func presentError(error: LocalizedError) {}
    
    func presentBookmarkedLocations(response: Home.Location.Retrieve.Response) {
        presentBookmarkedLocationsCalled = true
    }
  }
  
  // MARK: Tests
  
  func testLoadBookmarkedLocations()
  {
    // Given
    let spy = HomePresentationLogicSpy()
    sut.presenter = spy
    
    // When
    sut.loadBookmarkedLocations()
    
    // Then
    XCTAssertTrue(spy.presentBookmarkedLocationsCalled, "doSomething(request:) should ask the presenter to format the result")
  }
}
